name: Cache Dependency
description: This action will use the previous cache Dependency if nothing changed
runs:
  using: composite
  steps:
    - name: Cache dependencies
      id: cache-vendor
      uses: actions/cache@v4
      with:
        path: vendor
        key: vendor-app-${{ hashFiles('**/composer.lock') }}

    - name: Install dependencies
      shell: bash
      if: steps.cache-vendor.outputs.cache-hit != 'true'
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist


